//
// Created by 22584 on 2023/12/21.
//

#ifndef SANDSIMULATION_OPENGL_CONSTANTS_H
#define SANDSIMULATION_OPENGL_CONSTANTS_H

const int CELL_WIDTH = 5;
const int CELL_HEIGHT = 5;
const int GRID_WIDTH_CELLS = 384;
const int GRID_HEIGHT_CELLS = 216;

#endif //SANDSIMULATION_OPENGL_CONSTANTS_H
